# Colors
COLOR_PRIMARY = "#1f538d"
COLOR_SUCCESS = "#4CAF50"
COLOR_WARNING = "#FF9800"
COLOR_ERROR = "#F44336"
COLOR_INFO = "#2196F3"

# Font sizes
FONT_TITLE = ("Roboto", 24, "bold")
FONT_HEADING = ("Roboto", 18, "bold")
FONT_SUBHEADING = ("Roboto", 14, "bold")
FONT_NORMAL = ("Roboto", 12)
FONT_SMALL = ("Roboto", 10)

# Spacing
PADDING_SMALL = 5
PADDING_MEDIUM = 10
PADDING_LARGE = 20

# Widget sizes
BUTTON_HEIGHT = 40
ENTRY_HEIGHT = 35
LIST_ROW_HEIGHT = 60

# Device status colors
STATUS_CONNECTED = COLOR_SUCCESS
STATUS_DISCONNECTED = COLOR_ERROR
STATUS_CHARGING = COLOR_INFO
STATUS_LOW_BATTERY = COLOR_WARNING